#!/bin/bash

stem="${1%.*}"
file="${stem}py"
path="../sbse14.wiki/${file}.md"
url="https://github.com/timm/sbse14/blob/master"

out=${url}/$1

src=$1
target=${path}
force=$2

if [ -n "$2" -o "$src" -nt "$target" ] 
then
(
cat<<EOF

# $stem

_View this source at [$stem]($out)._

____


EOF

cat $1 |
gawk --source '
BEGIN { First = 1
        In = 1}
/^"""</,/^>"""/ { next }

/^"""/ { In = 1 - In
         if (In) 
	     print "````python"
         else
	     if (First)
               First = 0
             else
               print "````"
         next
       }
{ print $0 }
END { if (In) print "````" }
' 
) > ${path}

echo ${path}

fi

